name: Build and Push Native Image (ARM64)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image for ARM64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker (ARM64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-native-image
          platforms: linux/arm64
          push: true
          tags: marcelo1980/projeto-gravador:latest
